name: Split, Deduplicate, and Upload Data to SQL Database

on:
  workflow_dispatch:

permissions:
  contents: write  

jobs:
  split_data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run split_data.py
        run: |
          python pipeline_scripts/split_data.py

      - name: Verify files created
        run: |
          if [ ! -f "customer_data_valid/customer_data_valid.xlsx" ] || [ ! -f "customer_data_invalid/customer_data_invalid.xlsx" ]; then
            echo "The required files were not created!";
            exit 1;
          fi

      - name: Commit splitted files
        run: |
          git config user.name "GitHub Actions"
          git config user.email "[email protected]"
          git pull origin main 
          git add customer_data_valid/customer_data_valid.xlsx customer_data_invalid/customer_data_invalid.xlsx
          git commit -m "Update splitted data [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deduplicate:
    runs-on: ubuntu-latest
    needs: split_data
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify input file for deduplication
        run: |
          if [ ! -f "customer_data_valid/customer_data_valid.xlsx" ]; then
            echo "Input file for deduplication is missing! Attempting to recreate...";
            python pipeline_scripts/split_data.py;
          fi

      - name: Run check_for_duplicates.py
        run: |
          python pipeline_scripts/check_for_duplicates.py

      - name: Commit deduplicated file
        run: |
          git config user.name "GitHub Actions"
          git config user.email "[email protected]"
          git pull origin main 
          git add customer_data_valid/customer_data_deduped.xlsx
          git commit -m "Update deduplicated data [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check_connection:
    runs-on: ubuntu-latest
    needs: deduplicate
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check database connection
        env:
          AZURE_SQL_SERVER: ${{ secrets.AZURE_SQL_SERVER }}
          AZURE_SQL_DATABASE: ${{ secrets.AZURE_SQL_DATABASE }}
          AZURE_SQL_USER: ${{ secrets.AZURE_SQL_USER }}
          AZURE_SQL_PASSWORD: ${{ secrets.AZURE_SQL_PASSWORD }}
        run: |
          python pipeline_scripts/check_db_connection.py

  upload_data:
    runs-on: ubuntu-latest
    needs: check_connection
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Force fetch and reset repository
        run: |
          git fetch --all
          git reset --hard origin/main

      - name: Verify deduplicated file exists
        run: |
          if [ ! -f "customer_data_valid/customer_data_deduped.xlsx" ]; then
            echo "Deduplicated file is missing in upload_data job!";
            exit 1;
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload deduplicated data to Azure SQL
        env:
          AZURE_SQL_SERVER: ${{ secrets.AZURE_SQL_SERVER }}
          AZURE_SQL_DATABASE: ${{ secrets.AZURE_SQL_DATABASE }}
          AZURE_SQL_USER: ${{ secrets.AZURE_SQL_USER }}
          AZURE_SQL_PASSWORD: ${{ secrets.AZURE_SQL_PASSWORD }}
        run: |
          python pipeline_scripts/upload_to_sql.py
