name: Clean Customer Data

on:
  push:
      

jobs:
  clean-data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Clean customer data
        run: python clean_up.py

      - name: Move clean data to cleaned_data folder
        run: |
          mkdir -p cleaned_data
          mv clean_data.xlsx cleaned_data/clean_data.xlsx

      - name: Move error data to validate_data folder
        run: |
          mkdir -p validate_data
          mv errors.xlsx validate_data/errors.xlsx

      - name: Commit and push cleaned and error files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add cleaned_data/clean_data.xlsx validate_data/errors.xlsx
          git commit -m "Add cleaned and error data files"
          git push origin main
