name: Split and Commit Data

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Viktigt för att kunna pusha tillbaka changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # så att vi kan göra nya commits

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pandas openpyxl Faker requests numpy

      - name: Run split_data.py
        run: |
          python pipeline_scripts/split_data.py
        # Detta script förväntas läsa 'customer_data.xlsx'
        # och skapa:
        #  - customer_data_valid/customer_data_valid.xlsx
        #  - customer_data_invalid/customer_data_invalid.xlsx

      - name: Commit splitted files
        run: |
          git config user.name "GitHub Actions"
          git config user.email "[email protected]"
          git add customer_data_valid/customer_data_valid.xlsx customer_data_invalid/customer_data_invalid.xlsx
          git commit -m "Update splitted data [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
